config/routes.rb
Work::Application.routes.draw do

  match '/about', to: 'pages#about', via: 'get'

  resources :reviews

  resources :orders

  resources :line_items

  resources :carts

  get 'static_pages/about'

  get 'static_pages/faq'

  get 'static_pages/term'

  resources :product_images

  resources :shippers

  resources :suppliers

  resources :products

  resources :manufacturers

  resources :categories

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  
  def total_price
	line_items.to_a.sum { |item| item.total_price }
  end
  def quantity
  line_items.to_a.sum { |item| item.quantity }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :order
	
	def total_price
		product.unit_price * quantity
	end

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
	belongs_to :user
	
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :product_image
	has_many :reviews
	has_many :line_items
	is_impressionable
	has_attached_file :photo, 
                    :styles => {
                      :thumb => "75x75>",
                      :small => "150x150>"
                    } 
def self.search(query)
  where("name like ?", "%#{query}%") 
end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
	belongs_to :product 
	has_attached_file :picture,
                    :styles => {
                      :thumb => "75x75>",
                      :small => "150x150>"
                    }
	validates_attachment_content_type :picture, :content_type => %w(image/jpeg image/jpg)
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :staff, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
has_many :reviews
has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
	@cart.destroy
	session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to(carts_url, :notice => 'Your cart is currently empty' ) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
    link_to title, :sort => column 
  end  
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_mailer_helper.rb
module UserMailerHelper
end

app/views/carts/_cart.html.erb
<ul class="nav navbar-nav navbar-right">
       
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="c"> <% if user_signed_in? %> Welcome <%= current_user.name %>, <% else %> Welcome Gruest <% end %>Cart (<%= cart.quantity %>) items<b class="caret"></b> *click to view cart</a>
          <ul class="dropdown-menu" id="cd">
            <div id="cart" >
				       <p id="notice"><%= notice %></p>
				<div class="cart_title" >Your Cart: <%= cart.quantity %> Items</div>
				<table>
				<%= render(cart.line_items) %>
				<tr class="total_line" >
				<td colspan="2" >Total</td>
				<td class="total_cell" ><%= number_to_currency(cart.total_price) %></td>
				</tr>
				</table>
				<%= button_to "Checkout" , new_order_path, :method => :get %>
				<%= button_to 'Empty cart' , cart, :method => :delete, :confirm => 'Are you sure?' %>
            </div>
          </ul>
        </li>
      </ul>


app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>