config/routes.rb
Work::Application.routes.draw do

  match '/about', to: 'pages#about', via: 'get'

  resources :reviews

  resources :orders

  resources :line_items

  resources :carts

  get 'static_pages/about'

  get 'static_pages/faq'

  get 'static_pages/term'

  resources :product_images

  resources :shippers

  resources :suppliers

  resources :products

  resources :manufacturers

  resources :categories

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  
  def total_price
	line_items.to_a.sum { |item| item.total_price }
  end
  def quantity
  line_items.to_a.sum { |item| item.quantity }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :order
	
	def total_price
		product.unit_price * quantity
	end

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
	belongs_to :user
	
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :product_image
	has_many :reviews
	has_many :line_items
	is_impressionable
	has_attached_file :photo, 
                    :styles => {
                      :thumb => "75x75>",
                      :small => "150x150>"
                    } 
def self.search(query)
  where("name like ?", "%#{query}%") 
end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
	belongs_to :product 
	has_attached_file :picture,
                    :styles => {
                      :thumb => "75x75>",
                      :small => "150x150>"
                    }
	validates_attachment_content_type :picture, :content_type => %w(image/jpeg image/jpg)
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :staff, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
has_many :reviews
has_many :orders
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
      @cart = current_cart
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
      @cart = current_cart
  @categories = Category.all
	@categories = Category.all
	@products = Product.where(:category_id => params[:id])
  @product_images = ProductImage.all
  end

  # GET /categories/new
  def new
      @cart = current_cart
  @categories = Category.all
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
      @cart = current_cart
  @categories = Category.all
  end

  # POST /categories
  # POST /categories.json
  def create
      @cart = current_cart
  @categories = Category.all
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
      @cart = current_cart
  @categories = Category.all
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
      @cart = current_cart
  @categories = Category.all
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
    link_to title, :sort => column 
  end  
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_mailer_helper.rb
module UserMailerHelper
end

app/views/categories/_cat.html.erb
<div class="col-md-2">
    <div class="side1">
      <div class="sidetop">
      CATEGORIES
      </div>
      
        <div id="category" >
          <%= render @categories %>
        </div>
    </div>
  </div>

app/views/categories/_categoris.html.erb
		<div class="side1">
			<div class="sidetop">
			Categories
			</div>
			
			<% @categories.each do |category| %>
			+<%= link_to category.name, category %> <br />
			 
			<% end %>
		</div>

app/views/categories/_category.html.erb
<li class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span><a class="sid"><%= link_to category.name, category, :class => 'sid' %></a> </li>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :created_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-md-2">
    <div class="side1">
      
        <ul class="list-group">
          <li class="list-group-item list-group-item-success"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li class="list-group-item list-group-item-info"><%= link_to 'Order History', orders_path %></li>
          <li class="list-group-item"></li>
          <li class="list-group-item list-group-item-warning"><b>Categories</b></li>
        <li class="list-group-item"><%= link_to 'All Categories', categories_path %></li>
        
          <%= render @categories %>
        </ul>
    </div>
  </div>
  <div class="col-md-10">
    <div class="side1">
      <div class="sidetop">
      <ol class="breadcrumb">
        <li><%= link_to 'Home', root_path, :class => 'sid' %></li></li>
        <li><%= link_to "category", categories_path, :class => 'sid' %></li>
      </ol>
      </div>
      <% if user_signed_in? %>
      <% if current_user.role == "admin" %>
      <%= link_to 'New Category', new_category_path, :class => 'btn btn-info btn-sm' %>
       <% end %>
       <% end %> 
      <h1>Listing categories</h1>
        <ul class="list-group">
         <% @categories.each do |category| %>
          <li class="list-group-item">
            <span class="badge">14 Products Available</span>
            <h3><b><%= category.name %></b></h3>
            <%= category.description %> <br />
            <%= link_to 'View Category', category, :class => 'btn btn-primary btn-sm' %> <% if !current_user.nil? and current_user.admin? %> | <%= link_to 'Edit', edit_category_path(category), :class => 'btn btn-info btn-sm' %> | <%= link_to 'Destroy', category, method: :delete, :class => 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } %> <% end %>
          </li>
         <% end %>
        </ul>
        
    </div>
  </div>
  
</div>


<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= category.created_at %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
-->
 <% if user_signed_in? %>
<% if current_user.role == "admin" %>
<%= link_to 'New Category', new_category_path %>
<% end %>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="row">
		<div class="col-md-2">
		<div class="side1">
			
				<ul class="list-group">
				  <li class="list-group-item list-group-item-success"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
				  <li class="list-group-item list-group-item-info"><%= link_to 'Order History', orders_path %></li>
				  <li class="list-group-item"></li>
				  <li class="list-group-item list-group-item-warning"><b>Categories</b></li>
				<li class="list-group-item"><%= link_to 'All Categories', categories_path %></li>
				
					<%= render @categories %>
				</ul>
		</div>
	</div>
	<div class="col-md-10">
		<div class="side1">
			<div class="sidetop">
			<ol class="breadcrumb">
			  <li><%= link_to 'Home', root_path, :class => 'sid' %></li></li>
			  <li><%= link_to "category", categories_path, :class => 'sid' %></li>
			  <li class="active"><%= @category.name %></li>
			</ol>
			</div>
			<div class="row">
				<% @products.each do |product| %>
			  <div class="col-md-4">
				<div class="prod">
					<div class="prod_img">
						<%= image_tag @product_images.first.picture.url %>
						
					</div>
					<div class="prod_txt"><%= product.name %><br />
					<b><%= number_to_currency(product.unit_price) %></b><br />
					<%= link_to('View Product', product, :class => 'btn btn-primary btn-sm')  %>
					<%= button_to 'Add to Cart' , line_items_path(:product_id => product), :remote => true %>
					<% if !current_user.nil? and current_user.admin? %>
					<%= link_to 'Edit', edit_product_path(product), :class => 'btn btn-info btn-sm' %>
					<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm' %>
					<% end %>
					</div>
				</div>
			   </div>
			   <% end %>
			</div>
		</div>
	</div>
	
</div>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @category.created_at %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

-->