config/routes.rb
Work::Application.routes.draw do

  match '/about', to: 'pages#about', via: 'get'

  resources :reviews

  resources :orders

  resources :line_items

  resources :carts

  get 'static_pages/about'

  get 'static_pages/faq'

  get 'static_pages/term'

  resources :product_images

  resources :shippers

  resources :suppliers

  resources :products

  resources :manufacturers

  resources :categories

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  
  def total_price
	line_items.to_a.sum { |item| item.total_price }
  end
  def quantity
  line_items.to_a.sum { |item| item.quantity }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :order
	
	def total_price
		product.unit_price * quantity
	end

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
	belongs_to :user
	
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :product_image
	has_many :reviews
	has_many :line_items
	is_impressionable
	has_attached_file :photo, 
                    :styles => {
                      :thumb => "75x75>",
                      :small => "150x150>"
                    } 
def self.search(query)
  where("name like ?", "%#{query}%") 
end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
	belongs_to :product 
	has_attached_file :picture,
                    :styles => {
                      :thumb => "75x75>",
                      :small => "150x150>"
                    }
	validates_attachment_content_type :picture, :content_type => %w(image/jpeg image/jpg)
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :staff, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
has_many :reviews
has_many :orders
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  impressionist actions: [:show], unique: [:session_hash]

  # GET /products
  # GET /products.json
  def index
    if params[:search]
    @products = Product.search(params[:search]).order("created_at DESC")
    else 
    @products = Product.order(params[:sort])
    end
     @cart = current_cart
	@categories = Category.all
  @product_images = ProductImage.all
  end

  # GET /products/1
  # GET /products/1.json
  def show

	@product_image = @product.product_image
	@categories = Category.all
     @cart = current_cart
      @reviews = Review.where(:product_id => params[:id])
     @review = Review.new

  end

  # GET /products/new
  def new
      @categories = Category.all
    @product = Product.new
     @cart = current_cart
  end

  # GET /products/1/edit
  def edit
      @categories = Category.all
     @cart = current_cart
  end

  # POST /products
  # POST /products.json
  def create
      @categories = Category.all
     @cart = current_cart
    @product = Product.new(product_params)
    @product_images = ProductImage.all
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
     @categories = Category.all
     @cart = current_cart
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
     @categories = Category.all
     @cart = current_cart
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :unit_price, :quantity, :manufacturer_id, :category_id, :created_at, :updated_at, :views, :available_size, :available_color, :quantity_sold)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
    link_to title, :sort => column 
  end  
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_mailer_helper.rb
module UserMailerHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product, html: { multipart: true }) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :unit_price %>
    <%= f.collection_select(:manufacturer_id,Manufacturer.all,:id,:name, {prompt: 'Select Manufacturer'}) %>
    <%= f.collection_select(:category_id,Category.all,:id,:name, {prompt: 'Select Category'}) %>
    <%= f.input :created_at %>
    <%= f.input :updated_at %>
    <%= f.input :available_size, :label => "Enter Default Picture Name"  %>
    <!--<%= f.input :available_color %>
    <%= f.input :photo %>-->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row">
	<div class="col-md-2">
		<div class="side1">
			
				<ul class="list-group">
				  <li class="list-group-item list-group-item-success"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
				  <li class="list-group-item list-group-item-info"><%= link_to 'Order History', orders_path %></li>
				  <li class="list-group-item"></li>
				  <li class="list-group-item list-group-item-warning"><b>Categories</b></li>
				<li class="list-group-item"><%= link_to 'All Categories', categories_path %></li>
				
					<%= render @categories %>
				</ul>
		</div>
	</div>
	<div class="col-md-10">
		<div class="side1">
			<div class="sidetop">
			<ol class="breadcrumb">
			  <li><%= link_to 'Home', root_path, :class => 'sid' %></li></li>
			  <li><%= link_to "Product", products_path, :class => 'sid' %></li>
			  
			</ol>
						Sort By: <%= sortable "name" %> | 
			<%= sortable "unit_price" %>
			<% if user_signed_in? %>
			 <% if current_user.role == "admin" %>
			<%= link_to 'New Product', new_product_path, :class => 'btn btn-sm btn-info' %>
			<% end %>
			<% end %>
			</div>
		

			<div class="row">
				<% @products.each do |product| %>
			  <div class="col-md-4">
				<div class="prod">
					<div class="prod_img">
						<%= image_tag @product_images.first.picture.url %>
						
					</div>
					<div class="prod_txt"><%= product.name %><br />
					<b><%= number_to_currency(product.unit_price) %></b><br />
					<%= link_to('View Product', product, :class => 'btn btn-primary btn-sm')  %>
					<%= button_to 'Add to Cart' , line_items_path(:product_id => product), :remote => true %>
					<% if !current_user.nil? and current_user.admin? %>
					<%= link_to 'Edit', edit_product_path(product), :class => 'btn btn-info btn-sm' %>
					<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm' %>
					<% end %>
					</div>
				</div>
			   </div>
			   <% end %>
			</div>
		</div>
	</div>
	
</div>
	<!--
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Unit price</th>
      <th>Quantity</th>
      <th>Manufacturer</th>
      <th>Category</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Views</th>
      <th>Available size</th>
      <th>Available color</th>
      <th>Quantity sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.unit_price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.manufacturer_id %></td>
        <td><%= product.category_id %></td>
        <td><%= product.created_at %></td>
        <td><%= product.updated_at %></td>
        <td><%= product.views %></td>
        <td><%= product.available_size %></td>
        <td><%= product.available_color %></td>
        <td><%= product.quantity_sold %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
-->
 <% if user_signed_in? %>
<% if current_user.role == "admin" %>
<%= link_to 'New Product', new_product_path, :class => 'btn btn-sm btn-info' %>
<% end %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
		<div class="col-md-2">
		<div class="side1">
			
				<ul class="list-group">
				  <li class="list-group-item list-group-item-success"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
				  <li class="list-group-item list-group-item-info"><%= link_to 'Order History', orders_path %></li>
				  <li class="list-group-item"></li>
				  <li class="list-group-item list-group-item-warning"><b>Categories</b></li>
				<li class="list-group-item"><%= link_to 'All Categories', categories_path %></li>
				
					<%= render @categories %>
				</ul>
		</div>
	</div>
	<div class="col-md-10">
		<div class="side1">
			<div class="sidetop">
			<ol class="breadcrumb">
			  <li><%= link_to 'Home', root_path, :class => 'sid' %></li></li>
			  <li><%= link_to "Product", products_path, :class => 'sid' %></li>
			  <li class="active"><%= @product.name %></li>
			</ol>
			</div>
			<div class="">
				<div class="col-md-5">
					
					<ol class="product_image">
						<%= render @product_image %>
					</ol>
					
					<br />
					
					<div class="clear"></div>
					<h1><%= "#{@product.impressionist_count} Views" %></h1>
					<%= button_to 'Add to Cart' , line_items_path(:product_id => @product.id), :remote => true %>
					<a href="mailto:dd@dd.com" class="btn btn-danger btn-sm">Send To Friend</a>
					<% if !current_user.nil? and current_user.admin? %>
					<%= link_to 'Edit', edit_product_path(@product), :class => 'btn btn-primary btn-sm' %>|<%= link_to 'Back', products_path, :class => 'btn btn-primary btn-sm' %>
					<% end %>
				</div>
				<div class="col-md-7">
					<p>
					  <strong>Name:</strong>
					  <%= @product.name %>
					</p>

					<p>
					  <strong>Description:</strong>
					  <%= @product.description %>
					</p>

					<p>
					  <strong>Unit price:</strong>
					  <%= @product.unit_price %>
					</p>

					<p>
					  <strong>Quantity:</strong>
					  <%= @product.quantity %>
					</p>

					<p>
					  <strong>Manufacturer:</strong>
					  <%= @product.manufacturer_id %>
					</p>

					<p>
					  <strong>Category:</strong>
					  <%= @product.category_id %>
					</p>

					<p>
					  <strong>Created at:</strong>
					  <%= @product.created_at %>
					</p>

					<p>
					  <strong>Updated at:</strong>
					  <%= @product.updated_at %>
					</p>

						


				</div>
			</div>
		</div>
		<div class="clear"></div>
		<h2>Reviews</h2>
			<div class="panel panel-danger">
			  <!-- Default panel contents -->
			  <div class="panel-heading">Reviews for <%= @product.name %></div>
			  <div class="panel-body">
			  <% if user_signed_in? %>
			    <%= simple_form_for(@review) do |f| %>
						  <%= f.error_notification %>

						  <div class="form-inputs">
						    
						    <%= f.input :review %>
						    <%=f.hidden_field :product_id, :value => @product.id %>
						  </div>

						  <div class="form-actions">
						    <%= f.button :submit %>
						  </div>
						<% end %>
						<% end %>
			  </div>

			  <!-- List group -->
			  <ul class="list-group">
			  <% @reviews.each do |review| %>
			    <li class="list-group-item">
			    <h3><%= review.username %></h3>
			    <p><%= review.review %></p>
			    </li>
			  <% end %>  	
			</div>
		
	</div>
	
</div>


<p id="notice"><%= notice %></p>


<!--
<h3>Pictures (<%= @product.product_image.count %>)</h3>
<ol class="product_image">
	<%= render @product_image %>
</ol>


<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @product.unit_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @product.manufacturer_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @product.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @product.updated_at %>
</p>

<p>
  <strong>Views:</strong>
  <%= @product.views %>
</p>

<p>
  <strong>Available size:</strong>
  <%= @product.available_size %>
</p>

<p>
  <strong>Available color:</strong>
  <%= @product.available_color %>
</p>

<p>
  <strong>Quantity sold:</strong>
  <%= @product.quantity_sold %>
</p>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
-->